config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/registrations#new"
  end
  root "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact-us"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo 2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar">
        <ul class="nav">
          <li class="nav-item"><%=  link_to "Home", root_path , class: "nav-link link-dark" %></li>
          <li class="nav-item"> <%=  link_to "About", about_path, class: "nav-link link-dark"  %> </li>
          <li class="nav-item"> <%=  link_to "Contact", contact_path, class: "nav-link link-dark"  %> </li>
          <li class="nav-item"> <%=  link_to "Sign In", signin_path, class: "nav-link link-dark"  %> </li>
          <li class="nav-item"> <%=  link_to "Sign Up", signup_path, class: "nav-link link-dark"  %> </li>
        </ul>
        <button class="btn btn-primary">
          <%= link_to "Log Out", signout_path, method: :delete, class: "text-light text-decoration-none"%>
        </button>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<%= stylesheet_link_tag "about"  %>
<div class="about">
  <h1>About Page</h1>
  <%= image_tag '1.jpg' %>
  <button class="btn btn-danger">CLick me</button>
</div>

app/views/pages/contact-us.html.erb
<div class="about">
  <h1>Contact US</h1>
</div>

app/views/pages/home.html.erb
<%= flash.each do |name,message| %>
  <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
<% end %>
<%if user_signed_in? %>
  <h1>Welcome back !</h1>
<%else%>
  <h1>Please <%= link_to "Sign In", "/users/sign_in"%> </h1>
<%end%>
<h1>Pages #home</h1>